config/routes.rb
Wtf2eat::Application.routes.draw do
  resources :dinners

end

app/models/dinner.rb
class Dinner < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dinners_controller.rb
class DinnersController < ApplicationController
  def index
    @dinners = Dinner.all
    @dinner  = @dinners[rand(@dinners.size)]
  end

  def new
    @dinner = Dinner.new
  end

  def create
    @dinner = Dinner.new(params[:dinner])
    @dinner.save
    redirect_to dinners_path
  end

  def edit
    @dinner = Dinner.find(params[:id])
  end

  def update
    @dinner = Dinner.find(params[:id])
    @dinner.update_attributes(params[:dinner])
    redirect_to dinners_path
  end

  def destroy
    @dinner = Dinner.find(params[:id])
    @dinner.destroy
    redirect_to dinners_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dinners/edit.html.erb
<%= form_for @dinner do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/dinners/index.html.erb
<%= @dinner.name %> <%= link_to '(edit)', edit_dinner_path(@dinner) %> <%= link_to '(delete)', @dinner, method: :delete %>
<br>
<%= link_to 'Get another dinner option', dinners_path %>
<br>
<%= link_to 'Add new dinner', new_dinner_path %>

app/views/dinners/new.html.erb
<%= form_for @dinner do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wtf2eat</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>